# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfhRN6gg_3ec-yQsK8wwxB2IEDd9mzQN
"""

# -*- coding: utf-8 -*-
"""
✈️  Flight Price Prediction — Realistic Booking Inputs (Fast Version)
======================================================================

KEY DIFFERENCE FROM ORIGINAL:
  ❌ OLD: used `distance` and `time`  →  internal airline columns, never
          collected from users on booking websites (MakeMyTrip, Kayak etc.)
  ✅ NEW: uses only what a booking form would ask:
          from city, to city, flight class, agency, date, passenger age

SPEED FIXES vs previous version:
  • RandomizedSearchCV: n_iter=10, cv=3  (30 fits, not 200)
  • Tuning runs on 30% sample when dataset > 20k rows
  • Random Forest capped at max 200 trees, max_depth ≤ 12
  • XGBoost / LightGBM preferred as best baseline (much faster to tune)
  • Baseline grid trimmed to 5 models
"""

# ── Imports ───────────────────────────────────────────────────────────────────
import os, json, warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, RandomizedSearchCV, KFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error,
    r2_score, mean_absolute_percentage_error,
)
from scipy.stats import randint, uniform
import joblib

try:
    from xgboost import XGBRegressor
    XGBOOST = True
except ImportError:
    XGBOOST = False
    print("[INFO] XGBoost not available — skipping.")

try:
    from lightgbm import LGBMRegressor
    LIGHTGBM = True
except ImportError:
    LIGHTGBM = False
    print("[INFO] LightGBM not available — skipping.")

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

print("✅ Imports done.")

# =============================================================================
# 1. LOAD DATA
# =============================================================================

# ── Update DATA_DIR to the folder where your CSVs live ───────────────────────
BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "dataset"
ARTIFACT_DIR = BASE_DIR / "artifacts"

flights_df = pd.read_csv(DATA_DIR / "flights.csv")
users_df = pd.read_csv(DATA_DIR / "users.csv")

print(f"flights : {flights_df.shape}")
print(f"users   : {users_df.shape}")
print(flights_df.head(3))

# Merge passenger age & gender
df = pd.merge(
    flights_df,
    users_df[["code", "gender", "age"]],
    left_on="userCode", right_on="code",
    how="left",
)
df["gender"] = df["gender"].fillna("none")
print(f"\nMerged shape: {df.shape}")

# =============================================================================
# 2. FEATURE ENGINEERING  (zero internal columns used)
# =============================================================================

# ── 2a. Date features ─────────────────────────────────────────────────────────
df["date"]        = pd.to_datetime(df["date"], dayfirst=False, infer_datetime_format=True)
df["month"]       = df["date"].dt.month
df["day_of_week"] = df["date"].dt.dayofweek    # 0=Mon … 6=Sun
df["is_weekend"]  = df["day_of_week"].isin([5, 6]).astype(int)
df["quarter"]     = df["date"].dt.quarter

# ── 2b. Route column ──────────────────────────────────────────────────────────
df["route"] = df["from"] + " → " + df["to"]
print(f"\nUnique routes : {df['route'].nunique()}")

# ── 2c. Ordinal flight class  (economy=0, premium=1, firstClass=2) ────────────
CLASS_ORDER = ["economic", "premium", "firstClass"]
CLASS_MAP   = {c: i for i, c in enumerate(CLASS_ORDER)}
df["flightClass_ord"] = df["flightType"].map(CLASS_MAP)

# ── 2d. Label encode cities, agency, gender ───────────────────────────────────
LE = {}   # store encoders for inference later

def fit_le(col):
    le = LabelEncoder()
    df[col + "_enc"] = le.fit_transform(df[col].astype(str))
    LE[col] = le

for col in ["from", "to", "agency", "gender"]:
    fit_le(col)

print("✅ Feature engineering done.")
print(df[["from", "to", "flightType", "agency", "date", "age",
          "flightClass_ord", "month", "route"]].head(3))

# =============================================================================
# 3. EDA  (quick — 3 charts)
# =============================================================================

fig, axes = plt.subplots(1, 3, figsize=(17, 4))

sns.boxplot(data=df, x="flightType", y="price",
            order=CLASS_ORDER, ax=axes[0], palette="Blues_r")
axes[0].set_title("Price by Flight Class")

sns.boxplot(data=df, x="agency", y="price",
            ax=axes[1], palette="Set2")
axes[1].set_title("Price by Agency")

monthly = df.groupby("month")["price"].mean()
axes[2].bar(monthly.index, monthly.values, color="#3949ab")
axes[2].set_title("Mean Price by Month")
axes[2].set_xlabel("Month")

plt.suptitle("EDA — price drivers without distance / time",
             fontsize=13, fontweight="bold", y=1.01)
plt.tight_layout()
plt.show()

# =============================================================================
# 4. TRAIN / VAL / TEST SPLIT  (route stats computed AFTER split to avoid leakage)
# =============================================================================

train_raw, test_raw = train_test_split(df, test_size=0.15, random_state=RANDOM_STATE)
train_raw, val_raw  = train_test_split(train_raw, test_size=0.176, random_state=RANDOM_STATE)

print(f"\nTrain : {len(train_raw):,}  |  Val : {len(val_raw):,}  |  Test : {len(test_raw):,}")

# =============================================================================
# 5. ROUTE & AGENCY STATS  (computed on train only — the key replacement for distance)
#
#  Why this works:
#    Real booking engines look up historical prices for each city-pair.
#    We replicate that by computing per-route price stats from training data.
#    This gives the model a strong price signal WITHOUT using internal distance/time.
# =============================================================================

route_stats = (
    train_raw.groupby("route")["price"]
    .agg(
        route_mean_price   = "mean",
        route_median_price = "median",
        route_min_price    = "min",
        route_max_price    = "max",
        route_count        = "count",
    )
    .reset_index()
)
route_stats["route_price_range"] = route_stats["route_max_price"] - route_stats["route_min_price"]

agency_stats = (
    train_raw.groupby("agency")["price"]
    .agg(agency_mean_price="mean")
    .reset_index()
)

# Global fallbacks for routes / agencies never seen in training
GLOBAL_ROUTE = {
    "route_mean_price":   train_raw["price"].mean(),
    "route_median_price": train_raw["price"].median(),
    "route_min_price":    train_raw["price"].min(),
    "route_max_price":    train_raw["price"].max(),
    "route_count":        1.0,
    "route_price_range":  train_raw["price"].max() - train_raw["price"].min(),
}
GLOBAL_AGENCY = {"agency_mean_price": train_raw["price"].mean()}

def enrich(split):
    out = split.merge(route_stats,  on="route",  how="left")
    out = out.merge(agency_stats, on="agency", how="left")
    for col, val in GLOBAL_ROUTE.items():
        out[col] = out[col].fillna(val)
    for col, val in GLOBAL_AGENCY.items():
        out[col] = out[col].fillna(val)
    return out

train_df = enrich(train_raw)
val_df   = enrich(val_raw)
test_df  = enrich(test_raw)

print("Route stats sample:")
print(route_stats.head(4))

# =============================================================================
# 6. FEATURE MATRIX
# =============================================================================

FEATURES = [
    # ── Booking form inputs ──────────────────────────────────────────────────
    "flightClass_ord",      # economy / premium / first  (ordinal 0-1-2)
    "from_enc",             # departure city
    "to_enc",               # destination city
    "agency_enc",           # booking platform
    "age",                  # passenger age
    "gender_enc",           # passenger gender

    # ── Date inputs (collected on form) ─────────────────────────────────────
    "month",
    "day_of_week",
    "is_weekend",
    "quarter",

    # ── Route & agency history (replaces distance) ───────────────────────────
    "route_mean_price",     # historical avg price on this city-pair
    "route_median_price",   # robust central tendency
    "route_min_price",      # cheapest ever seen
    "route_max_price",      # priciest ever seen
    "route_count",          # route popularity
    "route_price_range",    # price volatility
    "agency_mean_price",    # agency markup level
]

TARGET = "price"

X_train = train_df[FEATURES].astype(float)
y_train = train_df[TARGET]

X_val   = val_df[FEATURES].astype(float)
y_val   = val_df[TARGET]

X_test  = test_df[FEATURES].astype(float)
y_test  = test_df[TARGET]

print(f"\nFeature matrix: {X_train.shape}")

# =============================================================================
# 7. BASELINE MODEL COMPARISON  (fast — no hyperparameter search yet)
# =============================================================================

def metrics(y_true, y_pred, label=""):
    return {
        "label": label,
        "R2":   round(r2_score(y_true, y_pred), 4),
        "MAE":  round(mean_absolute_error(y_true, y_pred), 2),
        "RMSE": round(np.sqrt(mean_squared_error(y_true, y_pred)), 2),
        "MAPE": round(mean_absolute_percentage_error(y_true, y_pred) * 100, 2),
    }

# Scaler needed only for Ridge
scaler     = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_val_sc   = scaler.transform(X_val)
X_test_sc  = scaler.transform(X_test)

MODELS = {}

MODELS["Ridge"] = (
    Ridge(alpha=10).fit(X_train_sc, y_train),
    True   # use scaled
)
MODELS["Random Forest"] = (
    RandomForestRegressor(
        n_estimators=100, max_depth=10, min_samples_leaf=5,
        n_jobs=-1, random_state=RANDOM_STATE
    ).fit(X_train, y_train),
    False
)
MODELS["Gradient Boosting"] = (
    GradientBoostingRegressor(
        n_estimators=150, max_depth=5, learning_rate=0.1,
        subsample=0.8, random_state=RANDOM_STATE
    ).fit(X_train, y_train),
    False
)

if XGBOOST:
    MODELS["XGBoost"] = (
        XGBRegressor(
            n_estimators=150, max_depth=5, learning_rate=0.1,
            subsample=0.8, colsample_bytree=0.8,
            random_state=RANDOM_STATE, verbosity=0
        ).fit(X_train, y_train),
        False
    )

if LIGHTGBM:
    MODELS["LightGBM"] = (
        LGBMRegressor(
            n_estimators=150, max_depth=5, learning_rate=0.1,
            subsample=0.8, colsample_bytree=0.8,
            random_state=RANDOM_STATE, verbose=-1
        ).fit(X_train, y_train),
        False
    )

print(f"\n{'Model':<20}  {'R²':>6}  {'MAE':>8}  {'RMSE':>8}  {'MAPE':>7}")
print("─" * 58)

baseline_results = {}
for name, (model, scaled) in MODELS.items():
    Xv = X_val_sc if scaled else X_val
    m  = metrics(y_val, model.predict(Xv), label=name)
    baseline_results[name] = m
    print(f"  {name:<20}  {m['R2']:>6}  {m['MAE']:>8.2f}  "
          f"{m['RMSE']:>8.2f}  {m['MAPE']:>6.2f}%")

best_name = max(baseline_results, key=lambda k: baseline_results[k]["R2"])
print(f"\n🏆 Best baseline: {best_name}")

# ── Bar chart ─────────────────────────────────────────────────────────────────
res_df = pd.DataFrame(baseline_results).T.reset_index(drop=True)
res_df = res_df.sort_values("R2", ascending=False)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
for ax, col, title in zip(axes, ["R2", "MAE", "RMSE"], ["R² ↑", "MAE ↓", "RMSE ↓"]):
    vals = res_df[col].astype(float)
    bars = ax.barh(res_df["label"], vals,
                   color=["#1a237e","#3949ab","#5c6bc0","#7986cb","#9fa8da"][:len(res_df)],
                   edgecolor="white", height=0.55)
    ax.set_title(title, fontweight="bold")
    ax.invert_yaxis()
    for bar, v in zip(bars, vals):
        ax.text(bar.get_width() * 1.01, bar.get_y() + bar.get_height() / 2,
                f"{v}", va="center", fontsize=9)

plt.suptitle("Baseline Comparison (Validation Set)", fontsize=13,
             fontweight="bold", y=1.01)
plt.tight_layout()
plt.show()

# =============================================================================
# 8. FEATURE IMPORTANCE
# =============================================================================

best_model_obj, best_scaled = MODELS[best_name]

if hasattr(best_model_obj, "feature_importances_"):
    fi = pd.Series(best_model_obj.feature_importances_, index=FEATURES).sort_values()
    plt.figure(figsize=(8, 5))
    fi.plot(kind="barh", color="#3949ab")
    plt.title(f"Feature Importance — {best_name}", fontweight="bold")
    plt.xlabel("Importance")
    plt.tight_layout()
    plt.show()
    print("\nTop 5 features:")
    print(fi.sort_values(ascending=False).head(5))

# =============================================================================
# 9. HYPERPARAMETER TUNING  (FAST — 10 iterations, cv=3, 30% sample)
#
#  Total fits = n_iter × cv = 10 × 3 = 30  →  finishes in minutes not hours
# =============================================================================

PARAM_GRIDS = {
    "XGBoost": {
        "n_estimators":     randint(100, 400),
        "max_depth":        randint(3, 8),
        "learning_rate":    uniform(0.03, 0.15),
        "subsample":        uniform(0.6, 0.4),
        "colsample_bytree": uniform(0.6, 0.4),
        "reg_alpha":        uniform(0, 3),
        "reg_lambda":       uniform(0, 3),
    },
    "LightGBM": {
        "n_estimators":     randint(100, 400),
        "max_depth":        randint(3, 8),
        "learning_rate":    uniform(0.03, 0.15),
        "subsample":        uniform(0.6, 0.4),
        "colsample_bytree": uniform(0.6, 0.4),
        "reg_alpha":        uniform(0, 3),
        "reg_lambda":       uniform(0, 3),
    },
    "Gradient Boosting": {
        "n_estimators":     randint(100, 300),
        "max_depth":        randint(3, 7),
        "learning_rate":    uniform(0.03, 0.15),
        "subsample":        uniform(0.6, 0.4),
        "min_samples_leaf": randint(3, 20),
    },
    "Random Forest": {
        "n_estimators":     randint(100, 200),
        "max_depth":        randint(6, 12),
        "min_samples_leaf": randint(3, 15),
        "max_features":     ["sqrt", "log2"],
    },
    "Ridge": {
        "alpha": uniform(0.1, 50),
    },
}

param_grid = PARAM_GRIDS.get(best_name, {})

if param_grid:
    # ── Use 30% sample for speed when dataset is large ────────────────────────
    SAMPLE_FRAC = 0.30
    if len(X_train) > 20_000:
        idx      = np.random.choice(len(X_train), size=int(len(X_train) * SAMPLE_FRAC), replace=False)
        Xtr_tune = (X_train_sc if best_scaled else X_train).iloc[idx]
        ytr_tune = y_train.iloc[idx]
        print(f"[Tuning on {len(Xtr_tune):,} rows ({SAMPLE_FRAC*100:.0f}% sample) for speed]")
    else:
        Xtr_tune = X_train_sc if best_scaled else X_train
        ytr_tune = y_train

    kf = KFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)

    print(f"⚙️  Tuning {best_name}  (n_iter=10, cv=3 → 30 fits)...")
    search = RandomizedSearchCV(
        best_model_obj, param_grid,
        n_iter=10, cv=kf, scoring="r2",
        n_jobs=-1, random_state=RANDOM_STATE, verbose=1,
    )
    search.fit(Xtr_tune, ytr_tune)

    tuned_model    = search.best_estimator_
    best_params    = search.best_params_
    best_cv_score  = search.best_score_

    print(f"\n✅ Best CV R²: {best_cv_score:.4f}")
    print(f"   Best params: {best_params}")
else:
    print(f"No param grid for {best_name} — using baseline.")
    tuned_model   = best_model_obj
    best_params   = {}
    best_cv_score = baseline_results[best_name]["R2"]

# =============================================================================
# 10. FINAL TEST SET EVALUATION
# =============================================================================

Xte = X_test_sc if best_scaled else X_test
y_pred = tuned_model.predict(Xte)
test_m = metrics(y_test, y_pred, label=best_name)

print("\n" + "=" * 50)
print(f"  TEST SET RESULTS — {best_name} (tuned)")
print("=" * 50)
for k, v in test_m.items():
    if k != "label":
        print(f"  {k:<6}: {v}")

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].scatter(y_test, y_pred, alpha=0.25, color="#3949ab", s=4)
lims = [min(y_test.min(), y_pred.min()), max(y_test.max(), y_pred.max())]
axes[0].plot(lims, lims, "r--", lw=1.5)
axes[0].set_xlabel("Actual")
axes[0].set_ylabel("Predicted")
axes[0].set_title("Actual vs Predicted")

residuals = y_test.values - y_pred
axes[1].hist(residuals, bins=60, color="#5c6bc0", edgecolor="white")
axes[1].axvline(0, color="red", linestyle="--")
axes[1].set_xlabel("Residual")
axes[1].set_title("Residual Distribution")

plt.suptitle(f"Test Evaluation — {best_name}  R²={test_m['R2']}",
             fontsize=12, fontweight="bold", y=1.01)
plt.tight_layout()
plt.show()

# =============================================================================
# 11. SAVE ARTIFACTS
# =============================================================================

OUT = ARTIFACT_DIR
OUT.mkdir(exist_ok=True)

joblib.dump(tuned_model,  OUT / "model.joblib")
joblib.dump(scaler,       OUT / "scaler.joblib")
joblib.dump(LE,           OUT / "encoders.joblib")

route_stats.to_csv(OUT / "route_stats.csv",   index=False)
agency_stats.to_csv(OUT / "agency_stats.csv", index=False)

meta = {
    "model_name":    best_name,
    "best_params":   best_params,
    "features":      FEATURES,
    "test_metrics":  test_m,
    "cv_r2":         round(float(best_cv_score), 4),
    "train_rows":    len(X_train),
    "class_map":     CLASS_MAP,
    "global_route":  GLOBAL_ROUTE,
    "global_agency": GLOBAL_AGENCY,
    "le_classes":    {c: list(le.classes_) for c, le in LE.items()},
    "use_scaler":    best_scaled,
}
with open(OUT / "metadata.json", "w") as f:
    json.dump(meta, f, indent=2, default=str)

print("\n✅ Artifacts saved to ./artifacts/")
for p in sorted(OUT.iterdir()):
    print(f"   {p.name}  ({p.stat().st_size/1024:.1f} KB)")

# =============================================================================
# 12. INFERENCE FUNCTION  — accepts only booking-form inputs, no distance/time
# =============================================================================

def predict_price(
    from_city:   str,
    to_city:     str,
    flight_type: str,   # "economic" | "premium" | "firstClass"
    agency:      str,
    date:        str,   # "YYYY-MM-DD"
    age:         int   = 35,
    gender:      str   = "none",
) -> dict:
    """
    Predict flight price from inputs a booking website collects.

    Example
    -------
    predict_price(
        from_city="Recife (PE)",
        to_city="Florianopolis (SC)",
        flight_type="firstClass",
        agency="FlyingDrops",
        date="2024-06-15",
        age=34,
        gender="male",
    )
    """
    # Date
    d           = pd.to_datetime(date)
    month       = d.month
    dow         = d.dayofweek
    is_weekend  = int(dow in [5, 6])
    quarter     = d.quarter

    # Flight class
    if flight_type not in CLASS_MAP:
        raise ValueError(f"flight_type must be one of {list(CLASS_MAP)}")
    fc_ord = CLASS_MAP[flight_type]

    # Route stats
    route = f"{from_city} → {to_city}"
    rs    = route_stats[route_stats["route"] == route]
    if len(rs):
        r = rs.iloc[0]
        rmp, rmdp, rmin, rmax, rcnt, rrng = (
            r.route_mean_price, r.route_median_price,
            r.route_min_price,  r.route_max_price,
            r.route_count,      r.route_price_range,
        )
    else:
        rmp, rmdp = GLOBAL_ROUTE["route_mean_price"], GLOBAL_ROUTE["route_median_price"]
        rmin, rmax = GLOBAL_ROUTE["route_min_price"], GLOBAL_ROUTE["route_max_price"]
        rcnt, rrng = GLOBAL_ROUTE["route_count"],     GLOBAL_ROUTE["route_price_range"]

    # Agency stats
    ag  = agency_stats[agency_stats["agency"] == agency]
    amp = ag.iloc[0]["agency_mean_price"] if len(ag) else GLOBAL_AGENCY["agency_mean_price"]

    # Label encode
    def safe_enc(col, val):
        le = LE[col]
        return int(le.transform([val])[0]) if val in le.classes_ else 0

    row = pd.DataFrame([{
        "flightClass_ord":   fc_ord,
        "from_enc":          safe_enc("from",   from_city),
        "to_enc":            safe_enc("to",     to_city),
        "agency_enc":        safe_enc("agency", agency),
        "age":               age,
        "gender_enc":        safe_enc("gender", gender),
        "month":             month,
        "day_of_week":       dow,
        "is_weekend":        is_weekend,
        "quarter":           quarter,
        "route_mean_price":  rmp,
        "route_median_price":rmdp,
        "route_min_price":   rmin,
        "route_max_price":   rmax,
        "route_count":       rcnt,
        "route_price_range": rrng,
        "agency_mean_price": amp,
    }])[FEATURES].astype(float)

    if best_scaled:
        row = scaler.transform(row)

    price = float(tuned_model.predict(row)[0])
    return {
        "predicted_price": round(price, 2),
        "currency":        "BRL",
        "route":           route,
        "flight_type":     flight_type,
        "model":           best_name,
        "test_r2":         test_m["R2"],
    }

# =============================================================================
# 13. QUICK INFERENCE TEST
# =============================================================================

tests = [
    dict(from_city="Recife (PE)",    to_city="Florianopolis (SC)",
         flight_type="firstClass",   agency="FlyingDrops",
         date="2024-06-15", age=34,  gender="male"),

    dict(from_city="Brasilia (DF)",  to_city="Rio de Janeiro (RJ)",
         flight_type="economic",     agency="CloudFy",
         date="2024-11-20", age=28,  gender="female"),

    dict(from_city="Sao Paulo (SP)", to_city="Salvador (BH)",
         flight_type="premium",      agency="Rainbow",
         date="2024-03-08", age=55,  gender="none"),
]

print("\n" + "=" * 60)
print("  INFERENCE DEMO — booking-form inputs only (no distance)")
print("=" * 60)

for tc in tests:
    r = predict_price(**tc)
    print(f"\n  {r['route']}  |  {tc['flight_type']}  |  {tc['agency']}")
    print(f"  Predicted price : {r['predicted_price']} {r['currency']}")
    print(f"  Model           : {r['model']}  (Test R² = {r['test_r2']})")

# =============================================================================
# 14. SUMMARY
# =============================================================================

print("\n" + "=" * 60)
print("  SUMMARY")
print("=" * 60)
print(f"  Model     : {best_name}")
print(f"  Test R²   : {test_m['R2']}")
print(f"  Test MAE  : {test_m['MAE']}")
print(f"  Test RMSE : {test_m['RMSE']}")
print(f"  Test MAPE : {test_m['MAPE']}%")
print()
print("  ❌ Removed  : distance, time  (internal cols — not user-facing)")
print("  ✅ Replaced : route_mean/median/min/max/count/range")
print("               (historical price stats per city-pair — no leakage)")
print()
print("  User inputs the model accepts:")
print("    from city | to city | flight class | agency | date | age | gender")
print("=" * 60)




# Auto-download artifacts after every training run
